/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ufes.especificacao_mvp.view;

/**
 *
 * @author GVerner
 */
public class CategoriaProdutos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoriaProdutos.class.getName());

    /**
     * Creates new form CategoriaProdutos
     */
    public CategoriaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCategorias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCategoria = new javax.swing.JTextField();
        txtPercentualLucro = new javax.swing.JTextField();
        BtnNovo = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        btnExcluirCategoria = new javax.swing.JButton();
        btnSalvarCategoria = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnFechar = new javax.swing.JButton();
        lblModo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categorias de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Categorias Cadastradas"));

        tabelaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Categoria", "Percentual de lucro (%)"
            }
        ));
        tabelaCategorias.setShowHorizontalLines(true);
        tabelaCategorias.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tabelaCategorias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes da Categoria"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Categoria:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setText(" Percentual de lucro (%):");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel2.add(txtNomeCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 58, 464, -1));
        jPanel2.add(txtPercentualLucro, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 98, 139, -1));

        BtnNovo.setText("Novo");
        jPanel2.add(BtnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        BtnEditar.setText("Editar");
        jPanel2.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnExcluirCategoria.setText("Excluir");
        jPanel2.add(btnExcluirCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        btnSalvarCategoria.setText("Salvar");
        jPanel2.add(btnSalvarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        BtnCancelar.setText("Cancelar");
        jPanel2.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        BtnFechar.setText("Fechar");
        jPanel2.add(BtnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        lblModo.setText("Modo: Visualização");
        lblModo.setOpaque(true);
        jPanel2.add(lblModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CategoriaProdutos().setVisible(true));
    }
    
    public javax.swing.JTextField getTxtNomeCategoria() {
        return txtNomeCategoria;
    }

    public javax.swing.JTable getTabelaCategorias() {
        return tabelaCategorias;
    }

    public javax.swing.JButton getBtnSalvarCategoria() {
        return btnSalvarCategoria;
    }

    public javax.swing.JButton getBtnExcluirCategoria() {
        return btnExcluirCategoria;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton btnExcluirCategoria;
    private javax.swing.JButton btnSalvarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblModo;
    private javax.swing.JTable tabelaCategorias;
    private javax.swing.JTextField txtNomeCategoria;
    private javax.swing.JTextField txtPercentualLucro;
    // End of variables declaration//GEN-END:variables
}
